RegisterServerEvent("mine:addmoney")
AddEventHandler("mine:addmoney", function(iprice)
  TriggerEvent('es:getPlayerFromId', source, function(user)
        user:addMoney(tonumber(iprice))
  end)
end)

RegisterServerEvent("mine:getCash_s")
AddEventHandler("mine:getCash_s", function()
  TriggerEvent('es:getPlayerFromId', source, function(user)
    local argent = user:getMoney()
    TriggerClientEvent("mine:f_getCash", source, argent)
  end)
end)
