client_script('client/client.lua')

ui_page('client/html/index.html')

files({
  'client/html/index.html',
  'client/html/script.js',
  'client/html/style.css',
  'client/html/cursor.png',
	'client/html/img/14Street3.png',
	'client/html/img/14Street4.png',
	'client/html/img/14Street5.png',
	'client/html/img/15Standard8.png',
	'client/html/img/15Standard11.png',
	'client/html/img/15Standard12.png',
	'client/html/img/15Standard17.png',
	'client/html/img/15Standard19.png',
	'client/html/img/35Lowriders4.png',
	'client/html/img/39Hipster1.png',
	'client/html/img/39Hipster6.png',
	'client/html/img/39Hipster10.png',
	'client/html/img/Casual1.png',
	'client/html/img/Casual3.png',
	'client/html/img/party2.png',
	'client/html/img/2Beach2.png',
	'client/html/img/2Beach7.png',
	'client/html/img/2Beach8.png',
  'client/html/img/Femme1.png',
  'client/html/img/Femme2.png',
  'client/html/img/Femme3.png'
})
