RegisterServerEvent('lock:getCar')
AddEventHandler('lock:getCar', function()
  TriggerEvent('es:getPlayerFromId', source, function(user)
    TriggerClientEvent("lock:f_getCar", source, {user:getVehicle(), user:getJobVehicle()})
  end)
end)
